---
title: "Multivariate Data Analysis"
author: "Sarah Daly"
date: "September 15 2023"
output:
  word_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---
Purpose:  Create APC Histogram based on density category

Input Files:  Metadata.csv

#Set working directory
```{r}
setwd("C:/Users/dalys/OneDrive/Documents/My Documents/Cornell Postdoc Papers/Review paper/Manuscript/Code/APC Histogram")
list.files()
```

#Load Data
```{r}
df<- read.csv("Metadata .csv" , na.strings="NA")
samples_keep<- read.csv("keep_samples.csv")

#300 samples kept 
target<- samples_keep$ID

#Keep those 300 selected samples 
df_filtered <- df %>% 
  filter(sample.id %in% target)

dim(df_filtered) #Should be 300 long 
```

#histogram of APC and Reads
```{r}
library(ggplot2)
library(hrbrthemes)

# Colors by category
#(High="indianred",Medium="lightsalmon", Low = "skyblue")
#high graeter than equal 5, low equal or below 3
colors <- c(rep("skyblue",3), rep("lightsalmon",2), rep("indianred",5))

apc_hist<-ggplot(df_filtered, aes(x=APC_log)) + 
  geom_histogram(color="black", fill=colors, binwidth = 1)+
  theme(panel.grid.major=element_blank(), panel.grid.minor = element_blank(), #Remove background
panel.background = element_blank(), axis.line = element_line(colour = "black"))+
  theme(text = element_text(size=36,colour="black",face="bold"), 
       axis.text.x = element_text(angle=0,hjust = 2.5, siz=42,colour = 'black',margin=unit(c(0.25,0.25,0.25,0.25), "cm")),
     axis.text.y = element_text(angle = 0, hjust = 1, size=42, vjust=.5, colour = 'black',margin=unit(c(0.5,0.5,0.5,0.5), "cm")),
     axis.ticks.length = unit(-0.25, "cm"), #-0.25 #No tick marks
     plot.title= element_text(hjust = 0.9))+
ylab("No. Samples")+
  xlab(expression(bold("APC (log"["10"]~"CFU/sponge)")))+
  scale_y_continuous(expand = c(0, 0), breaks = seq(0,200, by=20))+
scale_x_continuous(expand = c(0,0),breaks = seq(0, 10, by = 1))+ #Force y axis to start at 0 0 
  theme(axis.ticks.x = element_blank()) # Remove x axis tick marks
  
apc_hist

tiff(paste("APC Histogram.tif", sep=" "), res=300, compression = "lzw", height=9, width=15, units="in")
print(apc_hist)
dev.off()

pdf("APC Histogram.pdf", width=15, height=9)
print(apc_hist)
dev.off()

```
